/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActionResponse {
  'globalStats' : [] | [{ 'natValue' : bigint }],
  'playerState' : PlayerState,
  'message' : string,
  'timestamp' : Timestamp,
  'successful' : boolean,
}
export interface Bonus {
  'hasNextUnlock' : boolean,
  'percentageUnlocked' : number,
  'fullyUnlocked' : boolean,
  'cntRemaining' : bigint,
  'locked' : number,
  'unlocked' : number,
  'unlocksRemaining' : bigint,
  'nextUnlockBalance' : number,
  'totqmy' : bigint,
  'remainingLocked' : number,
  'lastUnlockTimestamp' : bigint,
  'hasTokens' : boolean,
  'nextUnlockMessage' : string,
}
export interface CoinLock {
  'id' : string,
  'locked' : boolean,
  'lockedBy' : [] | [Principal],
  'timestamp' : [] | [Timestamp],
}
export type ExternalBlob = Uint8Array;
export interface Monster {
  'id' : string,
  'name' : string,
  'captured' : boolean,
  'captureTimestamp' : [] | [Timestamp],
}
export interface PlayerState {
  'id' : string,
  'xp' : bigint,
  'lockedQMY' : number,
  'coinLocks' : Array<CoinLock>,
  'lockedCoins' : Array<CoinLock>,
  'unlockedQMY' : number,
  'capturedMonsters' : Array<Monster>,
  'monsters' : Array<Monster>,
}
export interface SpawnItem {
  'id' : string,
  'latitude' : number,
  'attributes' : string,
  'longitude' : number,
  'itemType' : string,
  'spawnType' : string,
}
export type Timestamp = bigint;
export interface UserProfile {
  'name' : string,
  'locale' : string,
  'photoUrl' : [] | [ExternalBlob],
  'gender' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VestingEntry {
  'unlockTimestamp' : Timestamp,
  'installmentNumber' : bigint,
  'unlocked' : boolean,
  'amount' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'captureMonster' : ActorMethod<[string], ActionResponse>,
  'claimBonus' : ActorMethod<[], undefined>,
  'claimWelcomeBonus' : ActorMethod<[], undefined>,
  'getBonusStats' : ActorMethod<
    [],
    { 'maxUsers' : bigint, 'remaining' : bigint, 'registrationCount' : bigint }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClaimBonus' : ActorMethod<[], [] | [Bonus]>,
  'getPlayerState' : ActorMethod<[], PlayerState>,
  'getSpawnList' : ActorMethod<[], Array<SpawnItem>>,
  'getUserBonus' : ActorMethod<[Principal], [] | [Bonus]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVestingSchedule' : ActorMethod<[], Array<VestingEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lockCoin' : ActorMethod<[string], ActionResponse>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'setProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
  'unlockCoin' : ActorMethod<[string], ActionResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];