/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'locale' : IDL.Text,
  'photoUrl' : IDL.Opt(ExternalBlob),
  'gender' : IDL.Opt(IDL.Text),
});
export const Bonus = IDL.Record({
  'hasNextUnlock' : IDL.Bool,
  'percentageUnlocked' : IDL.Float64,
  'fullyUnlocked' : IDL.Bool,
  'cntRemaining' : IDL.Nat,
  'locked' : IDL.Float64,
  'unlocked' : IDL.Float64,
  'unlocksRemaining' : IDL.Nat,
  'nextUnlockBalance' : IDL.Float64,
  'totqmy' : IDL.Int,
  'remainingLocked' : IDL.Float64,
  'lastUnlockTimestamp' : IDL.Int,
  'hasTokens' : IDL.Bool,
  'nextUnlockMessage' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const CoinLock = IDL.Record({
  'id' : IDL.Text,
  'locked' : IDL.Bool,
  'lockedBy' : IDL.Opt(IDL.Principal),
  'timestamp' : IDL.Opt(Timestamp),
});
export const Monster = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'captured' : IDL.Bool,
  'captureTimestamp' : IDL.Opt(Timestamp),
});
export const PlayerState = IDL.Record({
  'id' : IDL.Text,
  'xp' : IDL.Nat,
  'coinLocks' : IDL.Vec(CoinLock),
  'monsters' : IDL.Vec(Monster),
});
export const ActionResponse = IDL.Record({
  'globalStats' : IDL.Opt(IDL.Record({ 'natValue' : IDL.Nat })),
  'playerState' : PlayerState,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'successful' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimBonus' : IDL.Func([], [], []),
  'getBonusStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'maxUsers' : IDL.Nat,
          'remaining' : IDL.Nat,
          'registrationCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClaimBonus' : IDL.Func([], [IDL.Opt(Bonus)], ['query']),
  'getPlayerState' : IDL.Func([], [PlayerState], ['query']),
  'getUserBonus' : IDL.Func([IDL.Principal], [IDL.Opt(Bonus)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lockCoin' : IDL.Func([IDL.Text], [ActionResponse], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unlockCoin' : IDL.Func([IDL.Text], [ActionResponse], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'locale' : IDL.Text,
    'photoUrl' : IDL.Opt(ExternalBlob),
    'gender' : IDL.Opt(IDL.Text),
  });
  const Bonus = IDL.Record({
    'hasNextUnlock' : IDL.Bool,
    'percentageUnlocked' : IDL.Float64,
    'fullyUnlocked' : IDL.Bool,
    'cntRemaining' : IDL.Nat,
    'locked' : IDL.Float64,
    'unlocked' : IDL.Float64,
    'unlocksRemaining' : IDL.Nat,
    'nextUnlockBalance' : IDL.Float64,
    'totqmy' : IDL.Int,
    'remainingLocked' : IDL.Float64,
    'lastUnlockTimestamp' : IDL.Int,
    'hasTokens' : IDL.Bool,
    'nextUnlockMessage' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const CoinLock = IDL.Record({
    'id' : IDL.Text,
    'locked' : IDL.Bool,
    'lockedBy' : IDL.Opt(IDL.Principal),
    'timestamp' : IDL.Opt(Timestamp),
  });
  const Monster = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'captured' : IDL.Bool,
    'captureTimestamp' : IDL.Opt(Timestamp),
  });
  const PlayerState = IDL.Record({
    'id' : IDL.Text,
    'xp' : IDL.Nat,
    'coinLocks' : IDL.Vec(CoinLock),
    'monsters' : IDL.Vec(Monster),
  });
  const ActionResponse = IDL.Record({
    'globalStats' : IDL.Opt(IDL.Record({ 'natValue' : IDL.Nat })),
    'playerState' : PlayerState,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'successful' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimBonus' : IDL.Func([], [], []),
    'getBonusStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'maxUsers' : IDL.Nat,
            'remaining' : IDL.Nat,
            'registrationCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClaimBonus' : IDL.Func([], [IDL.Opt(Bonus)], ['query']),
    'getPlayerState' : IDL.Func([], [PlayerState], ['query']),
    'getUserBonus' : IDL.Func([IDL.Principal], [IDL.Opt(Bonus)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lockCoin' : IDL.Func([IDL.Text], [ActionResponse], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unlockCoin' : IDL.Func([IDL.Text], [ActionResponse], []),
  });
};

export const init = ({ IDL }) => { return []; };